import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="h-screen bg-zinc-50 dark:bg-zinc-900">
          <div className="container mx-auto p-4 max-w-4xl">
            <NavBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}